TIMES = "Times"
OPTIONS = "options"
FIELDS = "fields"
ENUM = "enum"
TYPE = "type"
DEFAULT = "default"
OPTIONS_EXTEND = "options_extend"
GRPC = "grpc"
SERVICE = "service"
IMPORT = "import_package"
ARG = "arg"
RETURNS = "returns"
KEY = "key"
VALUE = "value"

